apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Release.Namespace }}
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_NAME: {{ .Values.mysql.database }}
  WORDPRESS_DB_USER: {{ .Values.mysql.user }}
