apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | required "mysql.rootPassword is required!" }}
  user-password: {{ .Values.mysql.password | required "mysql.password is required!" }}
